version: '3'
services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    networks:
      - ecommerce-network

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    networks:
      - ecommerce-network

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8084:8084"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge