spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoominmir41@gmail.com
    password: ugezyrwwifnlrnki
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

  data:
    redis:
      host: localhost
      port: 6379
